// <auto-generated />
using System;
using InventoryManagementSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryManagementSystem.Migrations
{
    [DbContext(typeof(IMSDbContext))]
    partial class IMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetAquisation", b =>
                {
                    b.Property<int>("AAid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AAid"));

                    b.Property<int>("AssetMasterId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("AAid");

                    b.HasIndex("AssetMasterId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("AssetAquisation");

                    b.HasData(
                        new
                        {
                            AAid = 1,
                            AssetMasterId = 1,
                            EmployeeId = 1,
                            ReceivedDate = new DateTime(2024, 10, 16, 23, 33, 44, 72, DateTimeKind.Local).AddTicks(3274),
                            Remark = "Received Successfully",
                            SerialNumber = 901,
                            Status = "Received",
                            VendorMasterId = 1
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetDeployement", b =>
                {
                    b.Property<int>("ADid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ADid"));

                    b.Property<int>("AssetMasterId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("ADid");

                    b.HasIndex("AssetMasterId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("AssetDeployement");

                    b.HasData(
                        new
                        {
                            ADid = 1,
                            AssetMasterId = 1,
                            DepartmentId = 1,
                            EmployeeId = 1,
                            IssueDate = new DateTime(2024, 10, 16, 23, 33, 44, 72, DateTimeKind.Local).AddTicks(3245),
                            Remark = "Deployed Successfully",
                            SerialNumber = 801,
                            Status = "Deployed",
                            VendorMasterId = 1
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetMaster", b =>
                {
                    b.Property<int>("AMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AMid"));

                    b.Property<string>("AssetDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.HasKey("AMid");

                    b.ToTable("AssetMaster");

                    b.HasData(
                        new
                        {
                            AMid = 1,
                            AssetDescription = "Dell XPS 13",
                            AssetModel = "Dell XPS",
                            AssetName = "Laptop",
                            SerialNumber = 601
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetProcurement", b =>
                {
                    b.Property<int>("APid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("APid"));

                    b.Property<int>("AssetMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchaseOrder")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("QuotationNumber")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorMasterId")
                        .HasColumnType("int");

                    b.HasKey("APid");

                    b.HasIndex("AssetMasterId");

                    b.HasIndex("VendorMasterId");

                    b.ToTable("AssetProcurement");

                    b.HasData(
                        new
                        {
                            APid = 1,
                            AssetMasterId = 1,
                            DeliveryDate = new DateTime(2024, 10, 23, 23, 33, 44, 72, DateTimeKind.Local).AddTicks(3219),
                            PurchaseDate = new DateTime(2024, 10, 16, 23, 33, 44, 72, DateTimeKind.Local).AddTicks(3214),
                            PurchaseOrder = 1001,
                            Quantity = 10,
                            QuotationNumber = 10001,
                            Remark = "On Time",
                            SerialNumber = 701,
                            Status = "Delivered",
                            VendorMasterId = 1
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("Depid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Depid"));

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Depid");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Depid = 1,
                            DepartmentDescription = "Human Resources",
                            DepartmentName = "HR",
                            SerialNumber = 301,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Designation", b =>
                {
                    b.Property<int>("Did")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Did"));

                    b.Property<string>("DesignaionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Did");

                    b.ToTable("Designation");

                    b.HasData(
                        new
                        {
                            Did = 1,
                            DesignaionDescription = "Manages teams",
                            DesignationName = "Manager",
                            SerialNumber = 201,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Eid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Eid"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DesignationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Serialnumber")
                        .HasColumnType("int")
                        .HasColumnName("Sr.No.");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eid");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("LocationId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Eid = 1,
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfJoining = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            DesignationId = 1,
                            Email = "john.doe@example.com",
                            EmpId = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            LocationId = 1,
                            Phone = "1234567890",
                            Serialnumber = 501,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Location", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lid"));

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Lid");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Lid = 1,
                            LocationDescription = "Headquarters",
                            LocationName = "HQ",
                            SerialNumber = 401,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("when")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Hossein.Sabzian@maine.edu",
                            Name = "Hossein",
                            Password = "RyanLove@@10",
                            SerialNumber = 55,
                            Status = "Active",
                            UserId = 1,
                            by = "Today",
                            when = new DateTime(2024, 10, 16, 23, 33, 44, 72, DateTimeKind.Local).AddTicks(2859)
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.VendorMaster", b =>
                {
                    b.Property<int>("VMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VMid"));

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("VendorDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VMid");

                    b.ToTable("VendorMaster");

                    b.HasData(
                        new
                        {
                            VMid = 1,
                            SerialNumber = 101,
                            VendorDescription = "Provides hardware",
                            VendorName = "TechVendor"
                        });
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetAquisation", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.AssetMaster", "AssetMaster")
                        .WithMany()
                        .HasForeignKey("AssetMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.VendorMaster", "VendorMaster")
                        .WithMany()
                        .HasForeignKey("VendorMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetMaster");

                    b.Navigation("Employee");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetDeployement", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.AssetMaster", "AssetMaster")
                        .WithMany()
                        .HasForeignKey("AssetMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.VendorMaster", "VendorMaster")
                        .WithMany()
                        .HasForeignKey("VendorMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetMaster");

                    b.Navigation("Department");

                    b.Navigation("Employee");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.AssetProcurement", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.AssetMaster", "AssetMaster")
                        .WithMany()
                        .HasForeignKey("AssetMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.VendorMaster", "VendorMaster")
                        .WithMany()
                        .HasForeignKey("VendorMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetMaster");

                    b.Navigation("VendorMaster");
                });

            modelBuilder.Entity("InventoryManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("InventoryManagementSystem.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InventoryManagementSystem.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
